apiVersion: v1
kind: Service
metadata:
  name: realbrand-frontend-service
  namespace: realbrand-pro
  labels:
    app: realbrand-frontend
    tier: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 3000
    protocol: TCP
    name: https
  selector:
    app: realbrand-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: realbrand-worker-service
  namespace: realbrand-pro
  labels:
    app: realbrand-worker
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: metrics
  selector:
    app: realbrand-worker
---
apiVersion: v1
kind: Service
metadata:
  name: realbrand-analytics-service
  namespace: realbrand-pro
  labels:
    app: realbrand-analytics
    tier: analytics
spec:
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: metrics
  selector:
    app: realbrand-analytics
---
apiVersion: v1
kind: Service
metadata:
  name: realbrand-redis-service
  namespace: realbrand-pro
  labels:
    app: realbrand-redis
    tier: cache
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: realbrand-redis

